[project]
name = "fastmcp-server-quickstart"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.4"
dependencies = [
    "fastapi>=0.100.0",
    "fastapi-mcp>=0.3.3",
    "fastmcp>=2.2.6",
    "pydantic>=2.0.0",
    "uvicorn>=0.22.0",
]
